modified curl command

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -67,11 +67,10 @@ jobs:
       - name: Test Main Project API
         run: |
           echo "Testing main project API..."
-          curl --fail -X POST \
-            -H "Content-Type: application/json" \
-            -d '{"threshold" : 0.9, "file": "https://as2.ftcdn.net/v2/jpg/03/21/17/83/1000_F_321178379_1PR3NpHHujbUtEfNGOLihMyfW2YO8Sjz.jpg"}' \
-            http://0.0.0.0:8085/api/v1/object-detect-count || (echo "API endpoint test failed" && exit 1)
+          curl -F "threshold=0.9" -F "file=@resources/images/boy.jpg" http://0.0.0.0:8085/object-detec-count || (echo "API endpoint test failed" && exit 1)
           curl --fail http://0.0.0.0:8085/health || (echo "Health check failed" && exit 1)
 
       - name: Stop Services
         run: docker-compose down
+
+        curl -F "threshold=0.9" -F "file=@resources/images/boy.jpg" http://0.0.0.0:8085/object-detec-count
